#!/usr/bin/env bash
# Cross-compiles the Windows-only sources with MinGW as an early warning on non-Windows hosts.
#
# What this proves: the plugin, the add-on's renderer, settings UI, icons, the Win32 named-pipe
# transport and the TeamSpeak SDK adapter all compile. That catches the ordinary mistakes --
# missing includes, wrong signatures, non-copyable types passed by value -- without waiting for
# a Windows machine.
#
# What it does NOT prove:
#   * That anything links. This is -fsyntax-only, so unresolved symbols are invisible to it.
#     A missing #include <reshade.hpp> in a file that calls ImGui passes here and then fails
#     at link on Windows -- that has actually happened. Only the MSVC job catches it.
#   * That the shipped binaries are correct. MSVC is the only supported compiler for a ReShade
#     add-on and the Windows CI job is authoritative.
# addon.cpp additionally cannot fully compile here: ReShade's own reshade.hpp casts a function
# pointer to void* with static_cast, which MSVC accepts as an extension and ISO C++ rejects.
# That error comes from ReShade's header, not from this project, so the script reports
# diagnostics originating in our own files separately and ignores that one.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CXX="${MINGW_CXX:-x86_64-w64-mingw32-g++}"

if ! command -v "$CXX" >/dev/null 2>&1; then
  echo "SKIP: $CXX not found (install mingw-w64, or set MINGW_CXX)"
  exit 0
fi
for dep in "$ROOT/third_party/reshade/include/reshade.hpp" "$ROOT/third_party/imgui/imgui.h" \
           "$ROOT/third_party/ts3client-pluginsdk/include/ts3_functions.h"; do
  if [[ ! -f "$dep" ]]; then
    echo "SKIP: missing $dep -- run scripts/fetch-deps.sh first"
    exit 0
  fi
done

# MinGW's headers are lower-case; ReShade includes <Windows.h>. On a case-sensitive filesystem
# that needs a shim, which is a property of cross-compiling, not of the code.
SHIM="$(mktemp -d)"
trap 'rm -rf "$SHIM"' EXIT
echo '#include <windows.h>' > "$SHIM/Windows.h"
# tsro/default_profile.hpp is generated by CMake from examples/profiles/default.json. Generate
# the same thing here so a syntax check does not need a configured build tree.
mkdir -p "$SHIM/tsro"
{
  echo '#ifndef TSRO_DEFAULT_PROFILE_HPP'
  echo '#define TSRO_DEFAULT_PROFILE_HPP'
  echo 'namespace tsro {'
  printf 'inline constexpr const char* kDefaultProfileJson = R"TSRO_JSON('
  cat "$ROOT/examples/profiles/default.json"
  echo ')TSRO_JSON";'
  echo '}'
  echo '#endif'
} > "$SHIM/tsro/default_profile.hpp"

INCLUDES=(
  -I"$SHIM"
  -I"$ROOT/shared/include"
  -I"$ROOT/reshade-integration/include"
  -I"$ROOT/teamspeak-plugin/include"
  -I"$ROOT/third_party/imgui"
  -I"$ROOT/third_party/reshade/include"
  -I"$ROOT/third_party/ts3client-pluginsdk/include"
)
# The .asi host sees no ReShade SDK at all -- that is the point of it.
ASI_INCLUDES=(
  -I"$SHIM"
  -I"$ROOT/shared/include"
  -I"$ROOT/reshade-integration/include"
  -I"$ROOT/asi-integration/include"
  -I"$ROOT/third_party/imgui"
)
# The warning set matches what CMake gives these sources on a real build, so a diagnostic that
# would fail CI fails here first. -Wshadow earns its place in particular: MSVC's C4457 (a local
# hiding a parameter) is an error under warnings-as-errors and -Wall -Wextra alone is silent
# about it. -Wconversion/-Wsign-conversion stand in for MSVC's C4244/C4267 at /W4.
FLAGS=(-std=c++17 -fsyntax-only -Wall -Wextra -Wshadow -Wconversion -Wsign-conversion
       -DTSRO_VERSION='"1.0.0"' -DTSRO_BUILD_ID='"check"'
       -DWIN32_LEAN_AND_MEAN -DNOMINMAX -include objbase.h)
# The renderer, settings UI, icons and font engine are shared with the .asi build, so they pick
# their host by definition. Checked here as the ReShade host; the .asi host is checked below
# against the vendored ImGui.
RESHADE_FLAGS=("${FLAGS[@]}" -DTSRO_HOST_RESHADE)

SOURCES=(
  shared/src/transport_win32.cpp
  shared/src/profile_store.cpp
  teamspeak-plugin/src/plugin.cpp
  teamspeak-plugin/src/plugin_core.cpp
  teamspeak-plugin/src/ts_state.cpp
  teamspeak-plugin/src/ts_query_ts3.cpp
  reshade-integration/src/overlay_host.cpp
  reshade-integration/src/icons.cpp
  reshade-integration/src/font_engine.cpp
  reshade-integration/src/renderer.cpp
  reshade-integration/src/settings_ui.cpp
)

status=0
for source in "${SOURCES[@]}"; do
  printf '%-42s ' "$source"
  if output="$("$CXX" "${RESHADE_FLAGS[@]}" "${INCLUDES[@]}" "$ROOT/$source" 2>&1)"; then
    echo "OK"
  else
    echo "FAIL"
    echo "$output" | head -20
    status=1
  fi
done

# addon.cpp is checked differently: only diagnostics from our own file count.
printf '%-42s ' "reshade-integration/src/addon.cpp"
output="$("$CXX" "${RESHADE_FLAGS[@]}" "${INCLUDES[@]}" "$ROOT/reshade-integration/src/addon.cpp" 2>&1)"
ours="$(echo "$output" | grep ": error" | grep "addon.cpp" || true)"
if [[ -n "$ours" ]]; then
  echo "FAIL"
  echo "$ours"
  status=1
else
  echo "OK (ReShade header errors under MinGW are expected; MSVC is authoritative)"
fi

# The .asi front end, and the shared overlay sources compiled as its host. Without
# TSRO_HOST_RESHADE the ImGui calls bind to the real library instead of ReShade's forwarders,
# which is a different compile of the same files and worth checking separately.
ASI_SOURCES=(
  asi-integration/src/asi_main.cpp
  asi-integration/src/overlay_window.cpp
  reshade-integration/src/overlay_host.cpp
  reshade-integration/src/icons.cpp
  reshade-integration/src/font_engine.cpp
  reshade-integration/src/renderer.cpp
  reshade-integration/src/settings_ui.cpp
)
for source in "${ASI_SOURCES[@]}"; do
  printf '%-42s ' "$source (.asi)"
  if output="$("$CXX" "${FLAGS[@]}" "${ASI_INCLUDES[@]}" "$ROOT/$source" 2>&1)"; then
    echo "OK"
  else
    echo "FAIL"
    echo "$output" | head -20
    status=1
  fi
done

exit $status
