#!/usr/bin/env bash
# Cross-builds the .asi front end with MinGW, all the way to a linked DLL.
#
# Why this exists: check-windows-sources.sh is -fsyntax-only, so unresolved symbols are
# invisible to it. The .asi build is exactly where that matters -- it links a real Dear ImGui
# instead of routing through ReShade's function table, so a missing source or a missing system
# library is a link error and nothing else. That class of mistake reached CI once already.
#
# What it does NOT prove: that the hooks work, or that a single frame draws. Neither can be
# tested without Windows and a running game; the MSVC job builds the shipped binary and a human
# has to try it. What it does prove is that every symbol the overlay references has a definition.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CXX="${MINGW_CXX:-x86_64-w64-mingw32-g++}"
CC="${MINGW_CC:-x86_64-w64-mingw32-gcc}"
RC="${MINGW_RC:-x86_64-w64-mingw32-windres}"

if ! command -v "$CXX" >/dev/null 2>&1 || ! command -v "$CC" >/dev/null 2>&1; then
  echo "SKIP: MinGW not found (install mingw-w64, or set MINGW_CXX/MINGW_CC)"
  exit 0
fi
for dep in "$ROOT/third_party/imgui/imgui.h" "$ROOT/third_party/minhook/include/MinHook.h"; do
  if [[ ! -f "$dep" ]]; then
    echo "SKIP: missing $dep -- run scripts/fetch-deps.sh first"
    exit 0
  fi
done

OUT="$(mktemp -d)"
trap 'rm -rf "$OUT"' EXIT
# MinGW's headers are lower-case; some Windows headers include <Windows.h>. On a case-sensitive
# filesystem that needs a shim, which is a property of cross-compiling, not of the code.
echo '#include <windows.h>' > "$OUT/Windows.h"
# tsro/default_profile.hpp is generated by CMake from examples/profiles/default.json. Generate
# the same thing here so a syntax check does not need a configured build tree.
mkdir -p "$OUT/tsro"
{
  echo '#ifndef TSRO_DEFAULT_PROFILE_HPP'
  echo '#define TSRO_DEFAULT_PROFILE_HPP'
  echo 'namespace tsro {'
  printf 'inline constexpr const char* kDefaultProfileJson = R"TSRO_JSON('
  cat "$ROOT/examples/profiles/default.json"
  echo ')TSRO_JSON";'
  echo '}'
  echo '#endif'
} > "$OUT/tsro/default_profile.hpp"

INCLUDES=(
  -I"$OUT"
  -I"$ROOT/shared/include"
  -I"$ROOT/reshade-integration/include"
  -I"$ROOT/asi-integration/include"
  -I"$ROOT/third_party/imgui"
  -I"$ROOT/third_party/minhook/include"
)
DEFINES=(-DTSRO_VERSION='"1.0.0"' -DTSRO_BUILD_ID='"check"' -DWIN32_LEAN_AND_MEAN -DNOMINMAX
         -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DIMGUI_DISABLE_DEMO_WINDOWS)

# Third-party: warnings here are not ours to fix, and MinHook is C.
THIRD_PARTY_C=(
  third_party/minhook/src/buffer.c
  third_party/minhook/src/hook.c
  third_party/minhook/src/trampoline.c
  third_party/minhook/src/hde/hde64.c
)
THIRD_PARTY_CXX=(
  third_party/imgui/imgui.cpp
  third_party/imgui/imgui_draw.cpp
  third_party/imgui/imgui_tables.cpp
  third_party/imgui/imgui_widgets.cpp
  third_party/imgui/backends/imgui_impl_dx11.cpp
  third_party/imgui/backends/imgui_impl_win32.cpp
)
# Ours. Note the absence of -DTSRO_HOST_RESHADE: that is what makes the shared overlay sources
# bind to the real ImGui rather than to ReShade's inline forwarders.
OURS=(
  asi-integration/src/asi_main.cpp
  asi-integration/src/d3d11_overlay.cpp
  reshade-integration/src/overlay_host.cpp
  reshade-integration/src/font_engine.cpp
  reshade-integration/src/renderer.cpp
  reshade-integration/src/settings_ui.cpp
  reshade-integration/src/icons.cpp
  shared/src/json.cpp
  shared/src/model.cpp
  shared/src/protocol.cpp
  shared/src/framing.cpp
  shared/src/state_store.cpp
  shared/src/config.cpp
  shared/src/config_enums.cpp
  shared/src/config_defaults.cpp
  shared/src/layout.cpp
  shared/src/notifications.cpp
  shared/src/log.cpp
  shared/src/ipc_server.cpp
  shared/src/overlay_client.cpp
  shared/src/profile_store.cpp
  shared/src/sqlite_read.cpp
  shared/src/ts_contacts.cpp
  shared/src/transport_win32.cpp
)

status=0
compile() {
  local compiler="$1"; shift
  local label="$1"; shift
  local extra="$1"; shift
  for source in "$@"; do
    printf '%-52s ' "$label $source"
    local object="$OUT/$(echo "$source" | tr '/' '_').o"
    if output="$("$compiler" -c -O1 $extra "${DEFINES[@]}" "${INCLUDES[@]}" \
                  -o "$object" "$ROOT/$source" 2>&1)"; then
      echo "OK"
    else
      echo "FAIL"
      echo "$output" | head -20
      status=1
    fi
  done
}

compile "$CC"  "[c ]" "-w" "${THIRD_PARTY_C[@]}"
compile "$CXX" "[3p]" "-w -std=c++17" "${THIRD_PARTY_CXX[@]}"
compile "$CXX" "[  ]" "-std=c++17 -Wall -Wextra -Wshadow -Wconversion -Wsign-conversion" "${OURS[@]}"

# The resource script. This is the part FiveM actually gates on: without FX_ASI_BUILD entries its
# loader refuses the plugin before DllMain runs, so a typo here is invisible at runtime -- there
# is no log of ours to read. CMake generates the .rc from the .in; do the same substitution here.
printf '%-52s ' "[rc] TeamSpeakOverlay.rc"
if command -v "$RC" >/dev/null 2>&1; then
  VERSION="$(sed -n 's/^project(.*VERSION \([0-9.]*\).*/\1/p' "$ROOT/CMakeLists.txt" | head -1)"
  VERSION="${VERSION:-1.0.0}"
  IFS=. read -r V_MAJOR V_MINOR V_PATCH <<< "$VERSION"
  sed -e "s/@PROJECT_VERSION_MAJOR@/${V_MAJOR}/g" \
      -e "s/@PROJECT_VERSION_MINOR@/${V_MINOR}/g" \
      -e "s/@PROJECT_VERSION_PATCH@/${V_PATCH}/g" \
      -e "s/@PROJECT_VERSION@/${VERSION}/g" \
      "$ROOT/asi-integration/TeamSpeakOverlay.rc.in" > "$OUT/TeamSpeakOverlay.rc"
  if output="$("$RC" -O coff -o "$OUT/zz_resources.o" "$OUT/TeamSpeakOverlay.rc" 2>&1)"; then
    echo "OK ($(grep -c '^FX_ASI_BUILD' "$OUT/TeamSpeakOverlay.rc") game builds declared)"
  else
    echo "FAIL"
    echo "$output" | head -20
    status=1
  fi
else
  echo "SKIP ($RC not found)"
fi

[[ $status -eq 0 ]] || exit 1

printf '%-52s ' "link TeamSpeakOverlay.asi"
if output="$("$CXX" -shared -o "$OUT/TeamSpeakOverlay.asi" "$OUT"/*.o \
              -ld3d11 -ldxgi -ld3dcompiler -ldwmapi -lgdi32 -ladvapi32 -lole32 -loleaut32 \
              -lshlwapi -static-libgcc -static-libstdc++ -static 2>&1)"; then
  echo "OK ($(stat -c %s "$OUT/TeamSpeakOverlay.asi") bytes)"
else
  echo "FAIL"
  echo "$output" | head -30
  status=1
fi

exit $status
